spring:
  profiles:
    active:
      - secret
      - local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/voilio?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: port
    password: port0429
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create #update
    properties:
      hibernate:
        show_sql: true  # 생성된 sql 출력
        format_sql: true
        use_sql_comments: true;
    show_sql: true
  servlet:
    multipart:
      max-file-size: 3GB
      max-request-size: 3GB
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    add-properties: false
  freemarker:
    cache: false
    suffix: .ftl
  batch:
    jdbc:
      initialize-schema: never
  mail:
    host: smtp.gmail.com
    port: 587
    username: gilyeon.dev
    password: hlorrqvtjgnklsxi
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha    # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha          # 태그 정렬 기준
    path: /swagger-ui.html      # html 문서 접속 경로
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none         # tag, operation 펼치는 방식
  paths-to-match:
    - /**

logging:
  level:
    org.springframework: info
    com.techeer.port.voilio : debug

jwt:
  secret: masdfafqawf65wdsadadcdwgzqpfoqmdyrkvuapfcjTTOwkfpOEsdcafafafaFEFFA1dfefaefGeAOgegIge3edw2ewfaffefa