spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-mysql:3306/voilio?serverTimezone=UTC&characterEncoding=UTF-8
    username: port
    password: port0429

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto : create #update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true;
    show_sql: true

logging:
  level:
    org:
      hibernate: info