spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/voilio?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto : update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show_sql: true

logging:
  level:
    org:
      hibernate: info