spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3306/voilio?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password:
=======
    url: jdbc:mysql://localhost:3306/voilio?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: port
    password: port0429
>>>>>>> d66ed0574e9ca9b12e4741faeb784f456daf71dc

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
<<<<<<< HEAD
      ddl-auto : update
=======
      ddl-auto: create #update
>>>>>>> d66ed0574e9ca9b12e4741faeb784f456daf71dc
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true;
    show_sql: true

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui.html # html 문서 접속 경로
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation 펼치는 방식
  paths-to-match:
    - /**

logging:
  level:
    org:
      hibernate: info